### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by xavier630** [diphtherial/factorio-autocar#2]
Hey, this mod looks really cool!

 I am planning to implement a feature for my mod (Ocean Liners) which is heavily inspired by this mod. The idea is that you can put down buoys to automate ship travel by sending the ship off in a certain direction when it hits the buoy. It's pretty much like this mod although the rotation is not relative to current direction. 

I was wondering if I would be able to please use your code for this feature (as it's nearly the same as what I am planning to do). I'd be happy to give you credit for it, and add you as a collaborator for the repository if you want too.

**Comment by xavier630** [comment]
Also, I especially like your solution in https://github.com/diphtherial/factorio-autocar/blob/master/prototypes/tile-prototypes.lua to avoid code duplication

**Comment by xavier630** [comment]
Okay, since you haven't replied, I'm just going to implement your ideas as per your license, thanks for open sourcing your code, it's really innovative!

**Comment by diphtherial** [comment]
Hey, sorry about that, haven't had access to a computer. I'm flattered that you like my code, and you're of course welcome to use it any way you like, with or without attribution. Good luck with your project!

**Comment by xavier630** [comment]
Thank you very much diphtherial, all the best,
